### ISSUE TITLE
Can't install pointnet++ with 'pip install .' And it should be 'python train_seg_pptr.py' rather than 'python train_pptr.py'(in README file).

### ISSUE THREAD

**Issue by HerocatUED** [hoi4d/HOI4D_SemSeg#4]
$ pip install .
Processing /mnt/sdc/wangx/HOI4D_SemSeg/modules
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pointnet2
  Building wheel for pointnet2 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'pointnet2._ext' extension
      Emitting ninja build file /mnt/sdc/wangx/HOI4D_SemSeg/modules/build/temp.linux-x86_64-cpython-39/build.ninja...
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/sdc/wangx/HOI4D_SemSeg/modules/setup.py", line 19, in <module>
          setup(
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1560, in _write_ninja_file_and_compile_objects
          _write_ninja_file(
        File "/home/wangx/anaconda3/envs/seg/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2102, in _write_ninja_file
          assert len(sources) > 0
      AssertionError
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pointnet2
  Running setup.py clean for pointnet2
Failed to build pointnet2
ERROR: Could not build wheels for pointnet2, which is required to install pyproject.toml-based projects

**Comment by SaiGP** [comment]
@HerocatUED I am facing the same issue. Have you solved this? Can you please guide on how did it?

**Comment by HerocatUED** [comment]
https://github.com/erikwijmans/Pointnet2_PyTorch
You can install this repo.

**Comment by SaiGP** [comment]
Thank got it!!!
