### ISSUE TITLE
Unable to install pointnet2

### ISSUE THREAD

**Issue by SaiGP** [hoi4d/HOI4D_SemSeg#6]
My system has CUDA 12.2, torch 2.4.0 and torchvision-0.19.0

when I run $> pip install .

I get the following error. Can you please tell me the compatible versions.

```
Processing /Data2/Hoi4D/HOI4D-SemSeg-main/modules
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pointnet2
  Building wheel for pointnet2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Data2/Hoi4D/hoienv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py'"'"'; __file__='"'"'/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xbsqzkci
       cwd: /Data2/Hoi4D/HOI4D-SemSeg-main/modules/
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_ext
  Emitting ninja build file /Data2/Hoi4D/HOI4D-SemSeg-main/modules/build/temp.linux-x86_64-3.8/build.ninja...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py", line 19, in <module>
      setup(
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
      build_ext.build_extensions(self)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
      _write_ninja_file_and_compile_objects(
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1771, in _write_ninja_file_and_compile_objects
      _write_ninja_file(
    File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2300, in _write_ninja_file
      assert len(sources) > 0
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for pointnet2
  Running setup.py clean for pointnet2
Failed to build pointnet2
Installing collected packages: pointnet2
    Running setup.py install for pointnet2 ... error
    ERROR: Command errored out with exit status 1:
     command: /Data2/Hoi4D/hoienv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py'"'"'; __file__='"'"'/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gqck6xn5/install-record.txt --single-version-externally-managed --compile --install-headers /Data2/Hoi4D/hoienv/include/site/python3.8/pointnet2
         cwd: /Data2/Hoi4D/HOI4D-SemSeg-main/modules/
    Complete output (55 lines):
    running install
    /Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_ext
    Emitting ninja build file /Data2/Hoi4D/HOI4D-SemSeg-main/modules/build/temp.linux-x86_64-3.8/build.ninja...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py", line 19, in <module>
        setup(
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 662, in run
        self.run_command('build')
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
        build_ext.build_extensions(self)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1771, in _write_ninja_file_and_compile_objects
        _write_ninja_file(
      File "/Data2/Hoi4D/hoienv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2300, in _write_ninja_file
        assert len(sources) > 0
    AssertionError

    ----------------------------------------

ERROR: Command errored out with exit status 1: /Data2/Hoi4D/hoienv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py'"'"'; __file__='"'"'/Data2/Hoi4D/HOI4D-SemSeg-main/modules/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gqck6xn5/install-record.txt --single-version-externally-managed --compile --install-headers /Data2/Hoi4D/hoienv/include/site/python3.8/pointnet2 Check the logs for full command output.
```

**Comment by SaiGP** [comment]
Used modules from https://github.com/hoi4d/HOI4D_ActionSeg it could help.
